### ISSUE TITLE
Add a method for obtaining pubkey from privkey

### ISSUE THREAD

**Issue by vsviridov** [Sirherobrine23/Wireguard-tools.js#16]
**Is your feature request related to a problem? Please describe.**
I'd like to have a functionality equivalent of `wg pubkey`

**Describe the solution you'd like**
Something along the lines of `function pubKey(privKey: string): string`

**Describe alternatives you've considered**
Currently I'm using `exec` with piping the private key into the `wg` binary.

**Comment by Sirherobrine23** [comment]
hello, I'm glad I can help you, for now I'm using an internal Wireguard utils to generate the keys, this function even includes an option to generate a `preshared key`.

example:

```

**Comment by Sirherobrine23** [comment]
But I'll think about putting this function too

**Comment by vsviridov** [comment]
I'm running a small VPN server, for which I've written some [management code](https://gitlab.com/vsviridov/wg-provision/). Today I've discovered your library and I'm now porting over from `wg-json` and running various `wg` commands to a native bridge...

I'm storing private keys in the config and just deriving pubkeys when necessary. So having something like this would certainly be nice.

**Comment by Sirherobrine23** [comment]
In my project example: https://github.com/OFVp-Project/Wireguard/blob/d522306362bd1f2478e04f02b519955618f36e64/src/Wireguard.ts#L46, I use it to add several users that are in the databases (mogodb), but I'm still having some problems.

**Comment by Sirherobrine23** [comment]
I still want to see why my network interface isn't going up, and why I can't connect.

**Comment by Sirherobrine23** [comment]
I will move your other issue here as well.

**Comment by vsviridov** [comment]
So, you essentially re-create the entire interface when you modify peers, I opted with adding peers one by one. I liked how you integrated `iptables` masquerading, should probably incorporate something similar.

I got the wireguard working manually first, and then added dynamic peer management once I was certain the setup is operational... So maybe debug your peers manually first. lmk if you want some help with that.

**Comment by Sirherobrine23** [comment]
I've never come close to `C/C++`, so I'm thinking it's a miracle it's able to add the peers. In order not to have to rewrite the whole thing, you would have to remove these lines:

```c++
   if (Config.IsEmpty()) return Napi::String::New(info.Env(), "Settings are empty");
   const Napi::String interfaceName = Config["name"].As<Napi::String>();
   wg_device wgDevice = {};
   // Copy name to device struct.
   if (interfaceName.IsEmpty()) return Napi::String::New(info.Env(), "Interface name is empty");
   if (interfaceName.Utf8Value().length() > sizeof(wgDevice.name) >= interfaceName.Utf8Value().length()) return Napi::String::New(info.Env(), "Interface name is too long");
   strncpy(wgDevice.name, interfaceName.Utf8Value().c_str(), interfaceName.Utf8Value().length());

   // Add interface
   int res = wg_add_device(wgDevice.name);
   if (res == -17);
   else if (res < 0) return Napi::String::New(info.Env(), "Error adding device");
```

**Comment by vsviridov** [comment]
looks like manipulating peers is calling `ipc_set_device` in https://github.com/WireGuard/wireguard-tools/blob/71799a8f6d1450b63071a21cad6ed434b348d3d5/src/set.c

**Comment by Sirherobrine23** [comment]
yes I know that, but there are a lot of different things when we call this function in each system it called somehow, on linux we use netlink to send all the configurations to Wireguard, on macos it's another way that I haven't looked at yet. I'm fixing some things yet, and I also have to see this part of the peers, I can take all the existing peers and add them from the javascript side, but it would be very confusing. That's why you have to leave all the peers inside an object because some peers may have been removed or added.

**Comment by Sirherobrine23** [comment]
I accepted migrating the key generations to the addon, the commit is this [`bea9155`](https://github.com/Sirherobrine23/Wireguard-tools.js/commit/bea91553885f9612868d7abf8a500238e1575bbc), but I still have to fix the [`src/add_device.cpp`](https://github.com/Sirherobrine23/Wireguard-tools.js/blob/0223cb7185c1bde9c57991e6ebcb45e413edce56/src/addon/add_device.cpp), I still haven't found the error.
