### ISSUE TITLE
Add methods for peer operations

### ISSUE THREAD

**Issue by vsviridov** [Sirherobrine23/Wireguard-tools.js#17]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the ability to manipulate peers from code

**Describe the solution you'd like**
Some methods to add peers, set keys, set allowed ips, etc...

**Describe alternatives you've considered**
Currently running `exec` with `wg set wg0 peer <pubkey> <...properties>`

**Comment by Sirherobrine23** [comment]
I added a function to work with peers (`peerOperation`), put the basic one, and now the wireguard interface is not fully recreated but any modification of the peer will be applied.
