### ISSUE TITLE
`allowedIPs` in the `peers` does not show the `CIDR` specifier.

### ISSUE THREAD

**Issue by vsviridov** [Sirherobrine23/Wireguard-tools.js#18]
It's quite important for routing, etc.

If I run `wg show wg0` I get following

```
peer: EPY2FPzhoN20+hsEKfsFtO/cjJvp1UzNTuU80l9J8hQ=
  allowed ips: 10.10.10.5/32, 192.168.1.0/24
```
But if run
```
const { show } = require("wireguard-tools.js");
console.log(show('wg0').peers);
```
I get following. as you can see, it's missing the `/32` and `/24` CIDR prefixes.
```
'EPY2FPzhoN20+hsEKfsFtO/cjJvp1UzNTuU80l9J8hQ=': { allowedIPs: [ '10.10.10.5', '192.168.1.0' ] },
```

**Comment by Sirherobrine23** [comment]
In wg he add the prefix, in the module it is the raw value that comes directly from netlink.

**Comment by Sirherobrine23** [comment]
I will work on your issue #17 and #16 first, before working with mask calculate.

**Comment by Sirherobrine23** [comment]
Add CIDR to allowed ips, commit df8014137ebeb4ca404107049cc8df1fa1171e9e
